spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    # mybatis缓存的数据库，默认为第15个
    cacheDatabase: 15
    # mybatis缓存过期时间（单位：分钟），默认：30
    cacheExpire: 30
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis-test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root